### ISSUE TITLE
Help Page Issues

### ISSUE THREAD

**Issue by TomMiller95** [cdeck95/LinkUp#36]
Crashes when I had no General Topic field entered, and hit submit.
Still need to go in that class and clean it up, so not sure what else causes crashing.

**Comment by cdeck95** [comment]
I'll look into this

**Comment by cdeck95** [comment]
I removed the blank option. @TomMiller95 please try to break it again and see if anything else is going wrong. If there is something else, submit a new issue or re-open this one.
