### ISSUE TITLE
Settings View - Edit App Button View

### ISSUE THREAD

**Issue by TomMiller95** [cdeck95/LinkUp#37]
Make sure all fields are not blank. Probably make The platform a combobox.
Custom SQL button needs to either go, or be made into a real button.

**Comment by cdeck95** [comment]
Custom SQL button should be removed. Keep method tho.

**Comment by cdeck95** [comment]
Also, no need for platform to be a combo box. We cannot have the user's editing that, but its there for informational purposes so they can make sure they know which app it is

**Comment by cdeck95** [comment]
Save button is now disabled if a field is blank. Also, custom sql button is gone.
