### ISSUE TITLE
Username is not displayed in the Edit Account Page

### ISSUE THREAD

**Issue by cdeck95** [cdeck95/LinkUp#55]
Need to parse the URL for the username, OR store username in the database and have it returned when getting all accounts.

**Comment by cdeck95** [comment]
Username column has been added to database

@cbporch add to the API model
I will add it to the iOS model

**Comment by TomMiller95** [comment]
I added username to the Apps class, and anywhere I could see it being used. Some places are commented out, and some are just using placeholders atm

**Comment by cdeck95** [comment]
Porch created the API code and I added the code to parse his response.
